use_frameworks!

platform :ios, '10.0'

target 'OTRuleHelper_Example' do
  pod 'OTRuleHelper', :path => '../'

  target 'OTRuleHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
